[project]
name = 'PeerReviewSystem'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.bug-bounty]
path = 'contracts/bug-bounty.clar'
clarity_version = 2
epoch = 2.5

[contracts.decentralized-charity_]
path = 'contracts/decentralized-charity_.clar'
clarity_version = 2
epoch = 2.5

[contracts.peer-review]
path = 'contracts/peer-review.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
